name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: |
        npm install
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Create API key configuration
      run: |
        echo "window.GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';" > public/api-config.js
      
    - name: Install Capacitor CLI
      run: |
        npm install -g @capacitor/cli
        
    - name: Sync Capacitor project
      run: |
        npx cap sync android
        
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        
    - name: Build with Gradle
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk